config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users, :controllers => {:omniauth_callbacks => "omniauth_callbacks"}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'welcome#index'

  namespace :admin do
    resources :levels do
      resources :challenges
    end
  end

  resources :levels do
    resources :challenges
  end

  resource :user

  resources :communities

  resources :tasks

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/challenge.rb
class Challenge < ApplicationRecord

  belongs_to :level
  
end

app/models/course.rb
class Course < ApplicationRecord
end

app/models/identity.rb
class Identity < ApplicationRecord
  belongs_to :user
end

app/models/level.rb
class Level < ApplicationRecord
  before_validation :generate_friendly_id, :on => :create

  mount_uploader :image, ImageUploader

  def to_param
    self.friendly_id
  end

  validates :title, presence: true
  validates :friendly_id, presence: true

  validates_uniqueness_of :friendly_id
  validates_format_of :friendly_id, :with => /\A[a-z0-9\-]+\z/

  has_many :challenges

  protected

  def generate_friendly_id
    self.friendly_id ||= SecureRandom.uuid
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  before_validation :uniq_username

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable


  mount_uploader :avatar, AvatarUploader

  def is_admin?
    self.role == "admin"
  end

  def display_name
    if self.username.present?
      self.username
    else
      self.email.split("@").first
    end
  end

  # GENDER = ["Male", "Female"]
  # validates_inclusion_of :gender, :in => GENDER

  validates :username, presence: true, length: {maximum: 25}

  has_many :identities

  def self.from_google(access_token, signed_in_resource=nil)
  	data = access_token.info
  	identity = Identity.find_by(:provider => access_token.provider, :uid => access_token.uid)

  	if identity
  		return identity.user
  	else
  		user = User.find_by(:email => access_token.email)
  		if !user
  			user = User.create(
  				username: data["name"],
  				email: data["email"],
  				avatar: MiniMagick::Image.open(data["image"]),
  				password: Devise.friendly_token[0,20],
          # gender: "Male",
  			)
  		end
			identity = Identity.create(
				provider: access_token.provider,
				uid: access_token.uid,
				user: user
			)
		return user
  	end
  end

  def self.from_facebook(access_token, signed_in_resoruce=nil)
		data = access_token.info
		identity = Identity.find_by(provider: access_token.provider, uid: access_token.uid)

		if identity
			return identity.user
		else
			user = User.find_by(:email => data.email)
			if !user
				user = User.create!(
					username: access_token.extra.raw_info.name,
					email: data.email,
					avatar: MiniMagick::Image.open(process_uri(data.image)),
					password: Devise.friendly_token[0,20],
          # gender: "Male",
				)
			end
			identity = Identity.create(
				provider: access_token.provider,
				uid: access_token.uid,
				user: user
			)
			return user
		end
  end



  private

  def self.process_uri(uri)
    require 'open-uri'
    require 'open_uri_redirections'
    open(uri, :allow_redirections => :safe) do |r|
      r.base_uri.to_s
    end
  end

  def uniq_username(name = self.username)
    if User.find_by(username: name)
      self.update_attributes(username: (name + rand(1000).to_s))
    end
  end


end

app/controllers/admin/levels_controller.rb
class Admin::LevelsController < ApplicationController
  before_action :authenticate_user!
  before_action :require_admin!
  layout "admin"

  def index
    @levels = Level.all
  end

  def new
    @level = Level.new
  end

  def create
    @level = Level.new(level_params)
    if @level.save
      redirect_to admin_levels_path
      flash[:notice] = "Level created!"
    else
      render :new
    end
  end

  def edit
    @level = Level.find_by_friendly_id!(params[:id])
  end

  def update
    @level = Level.find_by_friendly_id!(params[:id])
    if @level.update(level_params)
      redirect_to admin_levels_path
      flash[:notice] = "Level updated!"
    else
      render :edit
    end
  end

  def destroy
    @level = Level.find_by_friendly_id!(params[:id])
    @level.destroy
    redirect_to admin_levels_path
    flash[:alert] = "Level deleted!"
  end

  private

  def level_params
    params.require(:level).permit(:title, :image, :friendly_id)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  def require_admin!
    unless current_user.is_admin?
      flash[:alert] = "You are not admin!"
      redirect_to root_path
    end
  end

  protected

  def configure_permitted_parameters
		added_attrs = [:username, :email, :password, :password_confirmation, :remember_me]  #:gender
		devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
		devise_parameter_sanitizer.permit :account_update, keys: added_attrs<<:current_password
	end

end

app/controllers/challenges_controller.rb
class ChallengesController < ApplicationController

  def show
    @level = Level.find_by_friendly_id!(params[:level_id])
    @challenge = Challenge.find(params[:id])
  end


  private

  def challenge_params
    params.require(:challenge).permit(:title, :subtitle, :goal, :content, :task)
  end

end

app/controllers/communities_controller.rb
class CommunitiesController < ApplicationController

  def index
  end

end

app/controllers/levels_controller.rb
class LevelsController < ApplicationController

  def index
    @levels = Level.all
  end

  def show
    @level = Level.find_by_friendly_id!(params[:id])
    @challenges = @level.challenges
  end

end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < ApplicationController

  def google_oauth2
		@user = User.from_google(request.env["omniauth.auth"], current_user)

		if @user.persisted?
			flash[:notice] = I18n.t "devise.omniauth_callbacks.success", :kind => "Google"
			sign_in_and_redirect @user, :event => :authentication
		else
			session["devise.user_data"] = request.env["omniauth.auth"]
			redirect_to new_user_registration_path
		end
	end

  def facebook
  		@user = User.from_facebook(request.env["omniauth.auth"], current_user)
      
  		if @user.persisted?
  			flash[:notice] = I18n.t "devise.omniauth_callbacks.success", :kind => "Facebook"
  			sign_in_and_redirect @user, :event => :authentication
  		else
  			session["devise.user_data"] = request.env["omniauth.auth"]
  			redirect_to new_user_registration_path
  		end
  end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  def index
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :authenticate_user!

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    if @user.update(user_params)
      flash[:notice] = "Update success!"
      redirect_to edit_user_path
    else
      render :edit
    end
  end

  protected

  def user_params
    params.require(:user).permit(:username, :gender, :avatar)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
end

app/helpers/admin/levels_helper.rb
module Admin::LevelsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  def avatar_url(user, size)
    gravatar_id = Digest::MD5.hexdigest(user.email.downcase)
    "http://gravatar.com/avatar/#{gravatar_id}.png?s=#{size}&d=mm"
  end

  def render_user_avatar(user, size)
    if user.avatar.present?
      user.avatar.small
    else
      avatar_url(user, size)
    end
  end

end

app/helpers/challenges_helper.rb
module ChallengesHelper
end

app/helpers/communities_helper.rb
module CommunitiesHelper
end

app/helpers/flashes_helper.rb
module FlashesHelper
  FLASH_CLASSES = { alert: "danger", notice: "success", warning: "warning"}.freeze

  def flash_class(key)
    FLASH_CLASSES.fetch key.to_sym, key
  end

  def user_facing_flashes
    flash.to_hash.slice "alert", "notice","warning"
  end
end

app/helpers/levels_helper.rb
module LevelsHelper
end

app/helpers/omniauth_callbacks_helper.rb
module OmniauthCallbacksHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/admin/levels/_form.html.erb
<div class="group">
  <%= f.input :title, class: "form-control" %>
</div>

<div class="group">
  <%= f.label :friendly_id %>
  <%= f.text_field :friendly_id, require: true, class: "form-control" %>
  <p class="help-block">限小写英文、数字及横线，将作为网址的一部分</p>
</div>

<div class="group">
  <%= f.input :image, as: :file, class: "form-control" %>
</div>

<div class="group">
  <%= f.submit "Submit", data: { disable_with: "Submitting..." }, class: "btn btn-primary" %>
</div>

app/views/admin/levels/edit.html.erb
<div class="frame">

  <h2 class="text-center">Edit Level</h2>

  <%= simple_form_for [:admin, @level] do |f| %>

  <% if @level.image.present? %>
    <b>Current Pic</b> <br>
    <%= image_tag(@level.image.thumb) %>
  <% end %>

  <%= render :partial => "form", :locals => { :f => f } %>

  <% end %>

</div>

app/views/admin/levels/index.html.erb
<div class="frame">

  <div class="pull-right" style="padding-bottom: 20px;">
    <%= link_to("Create a New Level", new_admin_level_path, class: "btn btn-primary btn-sm") %>
  </div>

  <table class="table table-bordered">
    <thead>
      <tr>
        <th>Level Pic</th>
        <th>Level Name</th>
        <th>Go to Challenges</th>
        <th>Options</th>
      </tr>
    </thead>
    <tbody>
      <% @levels.each do |level| %>
        <tr>
          <td>
            <%= link_to level_path(level) do %>
              <% if level.image.present? %>
                <%= image_tag(level.image.small.url) %>
              <% else %>
                <%= image_tag("http://placehold.it/150x150&text=No Pic") %>
              <% end %>
            <% end %>
          </td>
          <td><%= link_to(level.title, edit_admin_level_path(level)) %></td>
          <td><%= link_to("Challenges", admin_level_challenges_path(level), class: "btn btn-warning btn-xs") %></td>
          <td>
            <%= link_to("Edit", edit_admin_level_path(level), class: "btn btn-primary btn-xs") %>
            <%= link_to("Delete", admin_level_path(level), method: :delete, class: "btn btn-danger btn-xs", data: { confirm: "Are you sure?" }) %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

</div>

app/views/admin/levels/new.html.erb
<div class="frame">

  <h2 class="text-center">New Level</h2>

  <%= simple_form_for [:admin, @level] do |f| %>

    <%= render :partial => "form", :locals => { :f => f } %>

  <% end %>

</div>

app/views/levels/index.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="dashboard-content">

      <!-- 左侧课程部分 -->
      <div class="left-section">
        <div class="course-content">

          <!-- 课程header 部分 -->
          <div class="dashboard-header col-xs-12">
            <h3>Game Start From Here</h3>
            <hr>
          </div>

          <!-- 课程内容部分 -->
          <div class="all-course">
            <div class="row">
              <% @levels.each do |level| %>
                <div class="col-md-4 col-xs-12">
                  <%= link_to level_path(level) do %>

                    <div class="level-card">
                      <div class="title-cover"></div>
                      <div class="start-btn">
                        <span>ENTER</span>
                      </div>
                      <div class="title">
                        <h4><%= level.title %></h4>
                      </div>
                      <div class="course-img">
                        <% if level.image.present? %>
                          <%= image_tag(level.image.thumb.url) %>
                        <% else %>
                          <%= image_tag("http://placehold.it/200x200&text=No Pic") %>
                        <% end %>
                      </div>
                      <div class="schedule-block">
                        <div class="percent-bar">
                          <div class="progress" id="hover-status"></div>
                        </div>
                        <p class="task">X / Y task(s) completed</p>
                      </div>
                    </div>

                  <% end %>
                </div>
              <% end %>
            </div>
          </div>

        </div>
      </div>

      <!-- 右侧卡片部分 -->
      <div class="right-section">

        <!-- 卡片 a -->
        <div class="right-section-card card-a">
          <div class="card-header">
            <div class="split">
              <h3>My Growth</h3>
            </div>
          </div>
          <hr>
          <div class="card-body text">
            <p>
              精灵 image <br>
              经验值：XXXX；<br>
              战斗力：XXXX；
            </p>
          </div>
        </div>

        <div class="right-section-card card-a">
          <div class="card-header">
            <div class="split">
              <h3>My Coins</h3>
            </div>
          </div>
          <hr>
          <div class="card-body text">
            <p>
              Hello Coins：XXXX；<br>
              Master Coins：XXXX；
            </p>
          </div>
        </div>

      </div>

    </div>
  </div>
</div>

app/views/levels/show.html.erb
<div class="course-menu" style="position: static; height: 65px; z-index: 1000;">
  <div class="menu-content" style="padding-top: 6px;">
    <div class="left-block hidden-xs">
      <h1><%= link_to(@level.title, level_path(@level))%></h1>
    </div>
  </div>
</div>

<div class="fixed" style="height: 0px;"></div>
<div class="flash-block"></div>

<div class="course-block" id="text-content">
  <div class="row">

    <div class="assignment-content" style="border-bottom: 1px solid #dedede;">
      <h1>My Progress</h1>
      <p>X / Y Task(s) Completed</p>
      <div class="small-progress-bar">
        <div class="progress">
          <div class="progress-bar" style="width: 325px; background-color: #bdbdbd;">
            0%
          </div>
        </div>
      </div>
    </div>

    <div class="group">
      <div class="syllabus">
        <table class="table-striped">
          <% @challenges.each do |challenge| %>
            <thead>
              <tr>
                <td id="section-name" colspan="2">
                  <h3 class="pull-left"><%= challenge.title %></h3>
                </td>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td class="post post-link">
                  <div style="height: 35px; overflow: hidden;">
                    <i class="fa fa-circle" style="color:#273748;"></i>
                    <%= link_to(challenge.subtitle, level_challenge_path(@level, challenge), style: "margin-left: 7px;") %>
                    <span></span> <span></span>
                  </div>
                </td>
              </tr>
            </tbody>
          <% end %>
        </table>
      </div>
    </div>

  </div>
</div>