config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users, :controllers => {:omniauth_callbacks => "omniauth_callbacks"}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'welcome#index'

  namespace :admin do
    resources :levels do
      resources :challenges
    end
  end

  resources :levels do
    resources :challenges
  end

  resource :user

  resources :communities

  resources :tasks

end

app/models/challenge.rb
class Challenge < ApplicationRecord

  belongs_to :level
  
end

app/controllers/admin/challenges_controller.rb
class Admin::ChallengesController < ApplicationController
  before_action :authenticate_user!
  before_action :require_admin!
  layout "admin"

  def index
    @level = Level.find_by_friendly_id!(params[:level_id])
    @challenges = @level.challenges
  end

  def new
    @level = Level.find_by_friendly_id!(params[:level_id])
    @challenge = Challenge.new
  end

  def create
    @level = Level.find_by_friendly_id!(params[:level_id])
    @challenge = Challenge.new(challenge_params)
    @challenge.level = @level
    if @challenge.save
      redirect_to admin_level_challenges_path(@level)
      flash[:notice] = "Challenge created"
    else
      render :new
    end
  end

  def edit
    @level = Level.find_by_friendly_id!(params[:level_id])
    @challenge = Challenge.find(params[:id])
  end

  def update
    @level = Level.find_by_friendly_id!(params[:level_id])
    @challenge = Challenge.find(params[:id])
    if @challenge.update(challenge_params)
      redirect_to admin_level_challenges_path(@level)
      flash[:notice] = "Challenge updated"
    else
      render :edit
    end
  end

  def destroy
    @level = Level.find_by_friendly_id!(params[:level_id])
    @challenge = Challenge.find(params[:id])
    @challenge.destroy
    redirect_to admin_level_challenges_path(@level)
    flash[:alert] = "Challenge deleted"
  end

  private

  def challenge_params
    params.require(:challenge).permit(:title, :subtitle, :goal, :content, :task)
  end

end

app/controllers/challenges_controller.rb
class ChallengesController < ApplicationController

  def show
    @level = Level.find_by_friendly_id!(params[:level_id])
    @challenge = Challenge.find(params[:id])
  end


  private

  def challenge_params
    params.require(:challenge).permit(:title, :subtitle, :goal, :content, :task)
  end

end

app/helpers/admin/challenges_helper.rb
module Admin::ChallengesHelper
end

app/helpers/challenges_helper.rb
module ChallengesHelper
end

app/views/admin/challenges/_form.html.erb
<div class="group">
  <%= f.input :title, class: "form-control" %>
</div>

<div class="group">
  <%= f.input :subtitle, class: "form-control" %>
</div>

<div class="group">
  <%= f.input :goal, class: "form-control" %>
</div>

<div class="group">
  <%= f.input :content, as: :ckeditor, class: "form-control" %>
</div>

<div class="group">
  <%= f.input :task, class: "form-control" %>
</div>

<div class="group">
  <%= f.submit "Submit", data: {disable_with: "Submitting..."}, class: "btn btn-primary" %>
</div>

app/views/admin/challenges/edit.html.erb
<div class="frame">

  <h2>Edit Challenges - Level <%= @level.title %></h2>

  <%= simple_form_for [:admin, @level, @challenge] do |f| %>

    <%= render :partial => "form", :locals => { :f => f } %>

  <% end %>

</div>

app/views/admin/challenges/index.html.erb
<div class="frame">

  <h1>Challenges - Level <%= @level.title %></h1>

  <div class="pull-right" style="padding-bottom: 20px;">
    <%= link_to("Create a New Challenge", new_admin_level_challenge_path(@level), class: "btn btn-primary btn-sm")%>
  </div>

  <table class="table table-bordered">
    <thead>
      <tr>
        <th>Title</th>
        <th>Subtitle</th>
        <th>Options</th>
      </tr>
    </thead>
    <tbody>
      <% @challenges.each do |challenge| %>
        <tr>
          <td><%= challenge.title %></td>
          <td><%= challenge.subtitle %></td>
          <td>
            <%= link_to("Edit", edit_admin_level_challenge_path(@level, challenge), class: "btn btn-primary btn-xs") %>
            <%= link_to("Delete", admin_level_challenge_path(@level, challenge), method: :delete, class: "btn btn-danger btn-xs", data: {confirm: "Are you sure?"}) %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

</div>

app/views/admin/challenges/new.html.erb
<div class="frame">

  <h2>Create Challenges - Level <%= @level.title %></h2>

  <%= simple_form_for [:admin, @level, @challenge] do |f| %>

    <%= render :partial => "form", :locals => { :f => f } %>

  <% end %>

</div>