config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users, :controllers => {:omniauth_callbacks => "omniauth_callbacks"}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'welcome#index'

  namespace :admin do
    resources :levels do
      resources :challenges
    end
  end

  resources :levels do
    resources :challenges
  end

  resource :user

  resources :communities

  resources :tasks

end

app/models/challenge.rb
class Challenge < ApplicationRecord

  belongs_to :level
  
end

app/controllers/admin/challenges_controller.rb
class Admin::ChallengesController < ApplicationController
  before_action :authenticate_user!
  before_action :require_admin!
  layout "admin"

  def index
    @level = Level.find_by_friendly_id!(params[:level_id])
    @challenges = @level.challenges
  end

  def new
    @level = Level.find_by_friendly_id!(params[:level_id])
    @challenge = Challenge.new
  end

  def create
    @level = Level.find_by_friendly_id!(params[:level_id])
    @challenge = Challenge.new(challenge_params)
    @challenge.level = @level
    if @challenge.save
      redirect_to admin_level_challenges_path(@level)
      flash[:notice] = "Challenge created"
    else
      render :new
    end
  end

  def edit
    @level = Level.find_by_friendly_id!(params[:level_id])
    @challenge = Challenge.find(params[:id])
  end

  def update
    @level = Level.find_by_friendly_id!(params[:level_id])
    @challenge = Challenge.find(params[:id])
    if @challenge.update(challenge_params)
      redirect_to admin_level_challenges_path(@level)
      flash[:notice] = "Challenge updated"
    else
      render :edit
    end
  end

  def destroy
    @level = Level.find_by_friendly_id!(params[:level_id])
    @challenge = Challenge.find(params[:id])
    @challenge.destroy
    redirect_to admin_level_challenges_path(@level)
    flash[:alert] = "Challenge deleted"
  end

  private

  def challenge_params
    params.require(:challenge).permit(:title, :subtitle, :goal, :content, :task)
  end

end

app/controllers/challenges_controller.rb
class ChallengesController < ApplicationController

  def show
    @level = Level.find_by_friendly_id!(params[:level_id])
    @challenge = Challenge.find(params[:id])
  end


  private

  def challenge_params
    params.require(:challenge).permit(:title, :subtitle, :goal, :content, :task)
  end

end

app/helpers/admin/challenges_helper.rb
module Admin::ChallengesHelper
end

app/helpers/challenges_helper.rb
module ChallengesHelper
end

app/views/challenges/show.html.erb
<div class="course-menu" style="position: static; height: 65px; z-index: 1000;">
  <div class="menu-content" style="padding-top: 6px;">
    <div class="left-block hidden-xs">
      <h1><%= link_to(@level.title, level_path(@level))%></h1>
    </div>
  </div>
</div>

<div class="fixed" style="height: 0px;"></div>
<div class="flash-block"></div>

<div class="course-block" id="show-content">
  <div class="row">

    <div class="post-visitor">
      <h4><%= @challenge.title %></h4>
    </div>

    <div class="course-post">

      <div class="post-title-h1 markdown">
        <h1><%= @challenge.subtitle %></h1>
      </div>

      <div class="post group">
        <div class="post-content markdown">
          <p>
            <div>
              <% if @challenge.goal.present? %>
                <h2>Goal</h2>
                <p><%= @challenge.goal %></p>
              <% end %>
            </div>
            <br>
            <div>
              <h2>Challenge</h2>
              <p><%= sanitize @challenge.content %></p>
            </div>
            <br>
            <div>
              <% if @challenge.task.present? %>
                <h2>Task</h2>
                <p><%= @challenge.task %></p>
                <%= link_to("Complete My Task", tasks_path, class: "btn btn-sm btn-default") %>
              <% end %>
            </div>
          </p>
        </div>
      </div>

      <div class="text-center", style="margin-top: 28px; margin-bottom: 20px;">
        <%= link_to("Back", level_path(@level), class: "general-btn")%>
      </div>

    </div>

  </div>
</div>