config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users, :controllers => {:omniauth_callbacks => "omniauth_callbacks"}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'welcome#index'

  namespace :admin do
    resources :levels do
      resources :challenges
    end
  end

  resources :levels do
    resources :challenges
  end

  resource :user

  resources :communities

  resources :tasks

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/challenge.rb
class Challenge < ApplicationRecord

  belongs_to :level
  
end

app/models/course.rb
class Course < ApplicationRecord
end

app/models/identity.rb
class Identity < ApplicationRecord
  belongs_to :user
end

app/models/level.rb
class Level < ApplicationRecord
  before_validation :generate_friendly_id, :on => :create

  mount_uploader :image, ImageUploader

  def to_param
    self.friendly_id
  end

  validates :title, presence: true
  validates :friendly_id, presence: true

  validates_uniqueness_of :friendly_id
  validates_format_of :friendly_id, :with => /\A[a-z0-9\-]+\z/

  has_many :challenges

  protected

  def generate_friendly_id
    self.friendly_id ||= SecureRandom.uuid
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  before_validation :uniq_username

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable


  mount_uploader :avatar, AvatarUploader

  def is_admin?
    self.role == "admin"
  end

  def display_name
    if self.username.present?
      self.username
    else
      self.email.split("@").first
    end
  end

  # GENDER = ["Male", "Female"]
  # validates_inclusion_of :gender, :in => GENDER

  validates :username, presence: true, length: {maximum: 25}

  has_many :identities

  def self.from_google(access_token, signed_in_resource=nil)
  	data = access_token.info
  	identity = Identity.find_by(:provider => access_token.provider, :uid => access_token.uid)

  	if identity
  		return identity.user
  	else
  		user = User.find_by(:email => access_token.email)
  		if !user
  			user = User.create(
  				username: data["name"],
  				email: data["email"],
  				avatar: MiniMagick::Image.open(data["image"]),
  				password: Devise.friendly_token[0,20],
          # gender: "Male",
  			)
  		end
			identity = Identity.create(
				provider: access_token.provider,
				uid: access_token.uid,
				user: user
			)
		return user
  	end
  end

  def self.from_facebook(access_token, signed_in_resoruce=nil)
		data = access_token.info
		identity = Identity.find_by(provider: access_token.provider, uid: access_token.uid)

		if identity
			return identity.user
		else
			user = User.find_by(:email => data.email)
			if !user
				user = User.create!(
					username: access_token.extra.raw_info.name,
					email: data.email,
					avatar: MiniMagick::Image.open(process_uri(data.image)),
					password: Devise.friendly_token[0,20],
          # gender: "Male",
				)
			end
			identity = Identity.create(
				provider: access_token.provider,
				uid: access_token.uid,
				user: user
			)
			return user
		end
  end



  private

  def self.process_uri(uri)
    require 'open-uri'
    require 'open_uri_redirections'
    open(uri, :allow_redirections => :safe) do |r|
      r.base_uri.to_s
    end
  end

  def uniq_username(name = self.username)
    if User.find_by(username: name)
      self.update_attributes(username: (name + rand(1000).to_s))
    end
  end


end

app/controllers/challenges_controller.rb
class ChallengesController < ApplicationController

  def show
    @level = Level.find_by_friendly_id!(params[:level_id])
    @challenge = Challenge.find(params[:id])
  end


  private

  def challenge_params
    params.require(:challenge).permit(:title, :subtitle, :goal, :content, :task)
  end

end

app/controllers/levels_controller.rb
class LevelsController < ApplicationController

  def index
    @levels = Level.all
  end

  def show
    @level = Level.find_by_friendly_id!(params[:id])
    @challenges = @level.challenges
  end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  def index
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :authenticate_user!

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    if @user.update(user_params)
      flash[:notice] = "Update success!"
      redirect_to edit_user_path
    else
      render :edit
    end
  end

  protected

  def user_params
    params.require(:user).permit(:username, :gender, :avatar)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper

  def avatar_url(user, size)
    gravatar_id = Digest::MD5.hexdigest(user.email.downcase)
    "http://gravatar.com/avatar/#{gravatar_id}.png?s=#{size}&d=mm"
  end

  def render_user_avatar(user, size)
    if user.avatar.present?
      user.avatar.small
    else
      avatar_url(user, size)
    end
  end

end

app/helpers/challenges_helper.rb
module ChallengesHelper
end

app/helpers/communities_helper.rb
module CommunitiesHelper
end

app/helpers/flashes_helper.rb
module FlashesHelper
  FLASH_CLASSES = { alert: "danger", notice: "success", warning: "warning"}.freeze

  def flash_class(key)
    FLASH_CLASSES.fetch key.to_sym, key
  end

  def user_facing_flashes
    flash.to_hash.slice "alert", "notice","warning"
  end
end

app/helpers/levels_helper.rb
module LevelsHelper
end

app/helpers/omniauth_callbacks_helper.rb
module OmniauthCallbacksHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/common/_flashes.html.erb
<% if flash.any? %>
  <% user_facing_flashes.each do |key, value| %>
    <div class="alert alert-dismissable alert-<%= flash_class(key) %>">
      <button class="close" data-dismiss="alert">×</button>
      <%= value %>
    </div>
  <% end %>
<% end %>

app/views/common/_footer.html.erb
<footer class="text-center">
  <div class="footer-below">
      <p class="text-center">
        Copyright © 2017 Nyhau Chinese All Rights Reserved.
      </p>
  </div>
</footer>

app/views/common/_navbar.html.erb
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <a class="navbar-brand" href="/" style="margin-left: 10px;"><img src='<%= image_url 'logo.png' %>'></a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-left">
              <li><%= link_to('Course', levels_path, class: "nav-block", style: "margin-left: 10px;") %></li>
              <li><%= link_to('Community', communities_path, class: "nav-block") %></li>
              <li><%= link_to('Relevant Studies', '#', class: "nav-block") %></li>
            </ul>
            <ul class="nav navbar-nav navbar-right" style="margin-right: 10px;">
              <% if !current_user %>
                <li><%= link_to('Log in', new_user_registration_path, class: "navbar-box") %></li>
              <% else %>
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                    <img src= "<%= render_user_avatar(current_user, 28) %>">
                    <b class="caret"></b>
                  </a>
                  <ul class="dropdown-menu">
                    <% if current_user.is_admin? %>
                      <li><%= link_to("Admin Panel", admin_levels_path) %></li>
                    <% end %>
                    <li><%= link_to("My Profile", edit_user_path) %></li>
                    <li><%= link_to("Sign Out", destroy_user_session_path, method: :delete) %></li>
                  </ul>
                </li>
              <% end %>
            </ul>
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container-fluid -->
</nav>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Nyhau Chinese 后台</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <div class="flex-content">
      <%= render "common/navbar" %>
      <%= render "common/flashes" %>
      <div class="col-md-2">
        <ul class="nav nav-pills nav-stacked" style="max-width: 150px; margin-top: 50px;">
          <li class="active"><%= link_to("Levels", admin_levels_path) %></li>
        </ul>
      </div>
      <div class="col-md-9">
        <%= yield %>
      </div>
    </div>

    <%= render "common/footer" %>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Nyhau Chinese</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!--Google Fonts link-->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Baloo+Tammudu" rel="stylesheet">

    <link href="https://fonts.googleapis.com/css?family=PT+Sans" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Montserrat:500" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet">

  </head>

  <body>
    <div class="flex-content">
      <!-- <div class="row"> -->
        <%= render "common/navbar" %>
        <%= render "common/flashes" %>
        <%= yield %>
      <!-- </div> -->
    </div>

    <%= render "common/footer" %>
  </body>
</html>